# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  przelewy24.merchant_id: '%env(P24_MERCHANT_ID)%'
  przelewy24.pos_id: '%env(P24_POS_ID)%'
  przelewy24.api_key: '%env(P24_API_KEY)%'
  przelewy24.crc_key: '%env(P24_CRC_KEY)%'
  przelewy24.sandbox: '%env(bool:P24_SANDBOX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Przelewy24Service:
      arguments:
        $merchantId: '%przelewy24.merchant_id%'
        $posId: '%przelewy24.pos_id%'
        $apiKey: '%przelewy24.api_key%'
        $crcKey: '%przelewy24.crc_key%'
        $sandbox: '%przelewy24.sandbox%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
